# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clip <- function(x, a, b) {
    .Call('_geomutils_clip', PACKAGE = 'geomutils', x, a, b)
}

